apiVersion: v1
kind: Namespace
metadata:
  name: flask-app
---
kind: Service
apiVersion: v1
metadata:
  name: flask-app
  namespace: flask-app
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-app
  labels:
    app: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: rerdogantr/flaskapp:latest
        imagePullPolicy: Always
        env:
        - name: SERVICE_NAME
          value: "flask-app"
        - name: PORT
          value: "8000"
        - name: AUTO_TRACE_ENABLED
          value: "true"
        - name: AUTO_TRACE_INTERVAL
          value: "30"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://XXXXXXXXXX:4318"
        ports:
          - containerPort: 8000
            protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-app-ingress
  namespace: flask-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: flask-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-app
            port:
              number: 80
